### ISSUE TITLE
启动报错,是文件路径写错,修改如下

### ISSUE THREAD

**Issue by shejiewei** [wxgzgl/flinkx-web-ui#7]
路径:src->views->datax->dataQuality->index.vue

import RDBMSReader from './reader/RDBMSReader'
import HiveReader from './reader/HiveReader'
import HBaseReader from './reader/HBaseReader'
import MongoDBReader from './reader/MongoDBReader'

修改为
import RDBMSReader from '../json-build/reader/RDBMSReader'
import HiveReader from'../json-build/reader/RDBMSReader'
import HBaseReader from '../json-build/reader/RDBMSReader'
import MongoDBReader from '../json-build/reader/RDBMSReader'

**Comment by wxgzgl** [comment]
谢谢你的反馈，提交的代码已经合并到主分支了。

**Comment by wxgzgl** [comment]
> 路径:src->views->datax->dataQuality->index.vue
> 
> import RDBMSReader from './reader/RDBMSReader'
> import HiveReader from './reader/HiveReader'
> import HBaseReader from './reader/HBaseReader'
> import MongoDBReader from './reader/MongoDBReader'
> 
> 修改为
> import RDBMSReader from '../json-build/reader/RDBMSReader'
> import HiveReader from'../json-build/reader/RDBMSReader'
> import HBaseReader from '../json-build/reader/RDBMSReader'
> import MongoDBReader from '../json-build/reader/RDBMSReader'

谢谢你的反馈，提交的代码已经合并到主分支了。

**Comment by wxgzgl** [comment]
close
